import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";

const DEFAULT_SIMULATOR_NAME = "Marktplaats iPhone 14 Pro";
const DEFAULT_SIMULATOR_OS = "18.2";
const DEFAULT_SNAPSHOT_RELATIVE_PATH = "Tests/GeneratedSnapshotTests.swift";

async function walkFiles(dir, acc = []) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".git" || entry.name === "Pods") {
        continue;
      }
      await walkFiles(fullPath, acc);
      continue;
    }
    acc.push(fullPath);
  }
  return acc;
}

export function getSimulatorDestination() {
  const name = process.env.IOS_SIMULATOR_NAME || DEFAULT_SIMULATOR_NAME;
  const os = process.env.IOS_SIMULATOR_OS || DEFAULT_SIMULATOR_OS;
  return `platform=iOS Simulator,name=${name},OS=${os}`;
}

async function detectWorkspaceOrProject(projectPath) {
  const entries = await readdir(projectPath, { withFileTypes: true });
  const workspace = entries.find((e) => e.name.endsWith(".xcworkspace"))?.name;
  if (workspace) {
    return { type: "workspace", value: workspace };
  }
  const project = entries.find((e) => e.name.endsWith(".xcodeproj"))?.name;
  if (project) {
    return { type: "project", value: project };
  }
  return null;
}

export async function ensureSnapshotTestExists(projectPath, issueKey) {
  const allFiles = await walkFiles(projectPath);
  const hasSnapshot = allFiles.some((file) => /snapshot/i.test(path.basename(file)));
  if (hasSnapshot) {
    return { created: false, path: null };
  }

  const configured = process.env.IOS_SNAPSHOT_TEST_FILE || DEFAULT_SNAPSHOT_RELATIVE_PATH;
  const outputPath = path.isAbsolute(configured) ? configured : path.join(projectPath, configured);
  await mkdir(path.dirname(outputPath), { recursive: true });

  const content = `import XCTest

final class GeneratedSnapshotTests: XCTestCase {
    func testGeneratedSnapshotPlaceholder_${(issueKey || "issue").replace(/[^a-zA-Z0-9_]/g, "_")}() {
        // Placeholder snapshot test generated by pipeline.
        // Replace with real snapshot assertions in your preferred snapshot framework.
        XCTAssertTrue(true)
    }
}
`;
  await writeFile(outputPath, content, "utf8");
  return { created: true, path: outputPath };
}

export async function runIOSTests(projectPath, deps = {}) {
  const scheme = process.env.IOS_TEST_SCHEME;
  if (!scheme) {
    throw new Error("Missing IOS_TEST_SCHEME");
  }

  const destination = getSimulatorDestination();
  const workspace = process.env.IOS_WORKSPACE;
  const project = process.env.IOS_PROJECT;

  let targetArg = null;
  if (workspace) {
    targetArg = ["-workspace", workspace];
  } else if (project) {
    targetArg = ["-project", project];
  } else {
    const detected = await detectWorkspaceOrProject(projectPath);
    if (!detected) {
      throw new Error("Could not detect .xcworkspace or .xcodeproj. Set IOS_WORKSPACE or IOS_PROJECT.");
    }
    targetArg = detected.type === "workspace"
      ? ["-workspace", detected.value]
      : ["-project", detected.value];
  }

  const args = [...targetArg, "-scheme", scheme, "-destination", destination, "test"];
  const execute = deps.executeCommand || executeXcodebuild;
  return execute(projectPath, args);
}

function executeXcodebuild(cwd, args) {
  return new Promise((resolve, reject) => {
    const child = spawn("xcodebuild", args, { cwd });
    let output = "";

    child.stdout.on("data", (chunk) => {
      output += chunk.toString();
    });
    child.stderr.on("data", (chunk) => {
      output += chunk.toString();
    });
    child.on("error", (err) => reject(err));
    child.on("close", (code) => {
      const lines = output.split("\n").filter(Boolean);
      const tail = lines.slice(-40).join("\n");
      resolve({
        success: code === 0,
        exitCode: code,
        outputTail: tail,
      });
    });
  });
}

export async function ensureSnapshotsAndRunTests(issueKey, deps = {}) {
  const projectPath = process.env.TARGET_PROJECT_PATH;
  if (!projectPath) {
    throw new Error("Missing TARGET_PROJECT_PATH. Set it in your environment.");
  }
  const pathInfo = await stat(projectPath).catch(() => null);
  if (!pathInfo?.isDirectory()) {
    throw new Error(`TARGET_PROJECT_PATH does not exist or is not a directory: ${projectPath}`);
  }

  const snapshot = await ensureSnapshotTestExists(projectPath, issueKey);
  const testRun = await runIOSTests(projectPath, deps);
  return { snapshot, testRun, destination: getSimulatorDestination() };
}
